### ISSUE TITLE
Refactor User class not to extend DatabaseManager

### ISSUE THREAD

**Issue by macic** [mariuszjeruzal/PHPUnit#1]
https://github.com/mariuszjeruzal/PHPUnit/blob/541b652cfb3f4ac365b8efaca06a6b1eddcaffc5/src/User.php#L9

User object should not extend database manager. There are other ways to access database functions. This is mixing up two different types of entities.

**Comment by mariuszjeruzal** [comment]
Now... deleted 'extends DatabaseManager' from User class - now I am just simply loading DatabaseManager class into my User class. In the constructor of User class I have "$this->tools = new DatabaseManager();". BUT!! At the same time I am learning about Dependency Injection methods and I do not understand it right now. I am pretty sure that I am not following Dependency Injection method at that time. Will try to understand it...

**Comment by mariuszjeruzal** [comment]
edited again - I think now I am using Constructor injection method in User class

**Comment by macic** [comment]
and obviously git remove them from this repo
